Io project hawls
cuhk-haosun/cuhk-haosun.github.io pull request #17
Opened 2024-03-14 12:51 UTC by fpfcap

i put the hck markdown into the item blog and i wanna have a review first

2024-03-20 04:38 UTC, Milokita commented on _posts/2024-3-14 HCK.md
> +Hematopoietic cell kinase (HCK) as a therapeutic target in immune and cancer cells. Oncotarget, Vol. 6, No. 18(2015).
the ref format isn;t correct

2024-03-20 04:38 UTC, Milokita commented on _posts/2024-3-14 HCK.md
> +tags: news images
tags not correct

2024-03-20 04:39 UTC, Milokita requested changes

2024-03-20 04:39 UTC, Milokita commented on _posts/2024-3-14 HCK.md
> +categories: news
not correct

2024-04-09 07:20 UTC, fpfcap commented on _posts/2024-3-14 HCK.md
> +Hematopoietic cell kinase (HCK) as a therapeutic target in immune and cancer cells. Oncotarget, Vol. 6, No. 18(2015).
done

2024-04-09 08:15 UTC, Milokita approved these changes

2024-04-15 06:41 UTC, Milokita approved these changes

2024-04-15 06:43 UTC, merged